alias adb='sudo -i `which adb`'
alias dchroot='TERM=xterm dchroot'
alias ec=emacsclient
alias man='LANG=C man'
alias pstree='pstree -A'
alias screen='TERM=screen screen'
alias timidity='timidity --output-24bit'
alias vi='vim'
alias xc='xclip -selection clipboard'
alias xp='xclip -selection primary'
alias xs='xclip -selection secondary'
